server:
  port: 8082
#  context-path: /resource-service

logging:
 level:
  org.springframework.security: DEBUG
  
spring:
  application:
    name: my-app-name
  jmx:
    default-domain: my-app-nam